name: showcase_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.8
  showcase:
    path: ../.

flutter:
  uses-material-design: true
  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript/DancingScript-Regular.ttf
          weight: 400
        - asset: fonts/DancingScript/DancingScript-Bold.ttf
          weight: 700
